### ISSUE TITLE
Way to ignore a directory

### ISSUE THREAD

**Issue by emmahsax** [reviewdog/action-detect-secrets#16]
Is there a way to ignore a directory? We can set `workdir`, which tells us where to run the action. But it'd be nice if there was a way to ignore a list of directories.

**Comment by levonet** [comment]
Yes, you can pass arguments through `detect_secrets_flags`.
`detect-secrets` can ignore different cases, for example, you can ignore directories using regex:

```yaml
    - uses: reviewdog/action-detect-secrets@v0.4.1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
        workdir: ${{ matrix.project }}
        fail_on_error: 'true'
        detect_secrets_flags: --all-files --force-use-all-plugins --exclude-files (.git|.github/actions)/
```
